name: Update packages

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update submodules
      run: |
        git submodule update --remote
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .* * || exit 0
        git commit -m "Update submodules" || exit 0
        git push || exit 0

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
