name: Update packages

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Update submodules
      run: |
        git submodule update --remote
        git add .* *
        git commit -m "Update submodules"
        git push

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
